---
- name: Install PostgreSQL
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
    state: present
    update_cache: true

- name: Discover PG version directory
  ansible.builtin.shell: "ls -1 /etc/postgresql | sort -n | tail -1"
  register: pg_ver_dir

- name: Allow remote connections
  ansible.builtin.lineinfile:
    path: "/etc/postgresql/{{ pg_ver_dir.stdout }}/main/postgresql.conf"
    regexp: "^#?listen_addresses =.*"
    line: "listen_addresses = '{{ pg_listen_address }}'"

- name: Add pg_hba rule
  ansible.builtin.lineinfile:
    path: "/etc/postgresql/{{ pg_ver_dir.stdout }}/main/pg_hba.conf"
    line: "host all all 0.0.0.0/0 md5"
    create: no

- name: Restart PostgreSQL
  ansible.builtin.systemd:
    name: postgresql
    state: restarted
    enabled: true

- name: Create catalog DB and user
  become_user: postgres
  ansible.builtin.shell: |
    psql -tc "SELECT 1 FROM pg_database WHERE datname='{{ pg_db }}'" | grep -q 1 || psql -c "CREATE DATABASE {{ pg_db }};"
    psql -tc "SELECT 1 FROM pg_roles WHERE rolname='{{ pg_user }}'" | grep -q 1 || psql -c "CREATE USER {{ pg_user }} WITH ENCRYPTED PASSWORD '{{ pg_password }}';"
    psql -c "GRANT ALL PRIVILEGES ON DATABASE {{ pg_db }} TO {{ pg_user }};"
