[minio]
140.245.228.72

[postgres]
140.245.228.72

[spark_master]
140.245.228.72

[spark_workers]
16.112.18.12

[prefect_server]
140.245.228.72 ansible_ssh_private_key_file=/Users/vc/Documents/Algo/pem_keys/ubuntu-72.key ansible_user=ubuntu

[prefect_agents]
140.245.228.72 ansible_ssh_private_key_file=/Users/vc/Documents/Algo/pem_keys/ubuntu-72.key ansible_user=ubuntu
16.112.18.12 ansible_ssh_private_key_file=/Users/vc/Documents/Algo/pem_keys/sirobilt-script-test.pem ansible_user=ec2-user
