---
- name: Deploy Common Dependencies
  hosts: prefect_server,prefect_agents
  become: true
  vars_files:
    - roles/common/vars/main.yml
  roles:
    - role: common
      tags: [ 'common' ]

- name: Deploy Prefect with Work Pools
  hosts: prefect_server,prefect_agents
  become: true
  vars_files:
    - roles/common/vars/main.yml  # This was missing
  roles:
    - role: prefect
      tags: [ 'prefect' ]