---
- name: Deploy Data Stack
  hosts: all
  become: true
  vars_files:
    - roles/common/vars/main.yml
  roles:
    - role: common
      tags: [ 'common' ]

- name: Deploy MinIO
  hosts: minio
  become: true
  roles:
    - role: minio
      tags: [ 'minio' ]

- name: Deploy PostgreSQL
  hosts: postgres
  become: true
  roles:
    - role: postgresql
      tags: [ 'postgresql' ]

- name: Deploy Spark
  hosts: spark_master,spark_workers
  become: true
  roles:
    - role: spark
      tags: [ 'spark' ]

- name: Deploy Prefect
  hosts: prefect_server,prefect_agents
  become: true
  roles:
    - role: prefect
      tags: [ 'prefect' ]

- name: Configure UFW Firewall
  hosts: all
  become: true
  roles:
    - role: ufw
      tags: [ 'ufw' ]