---
# tasks file for roles/docker

- name: Remove old Docker GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    state: absent

- name: Remove old Docker repository file
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent

- name: Update apt package index
  ansible.builtin.apt:
    update_cache: true
  changed_when: false

- name: Install prerequisite packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - ufw
    state: present

- name: Create directory for Docker GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Set permissions for Docker GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.gpg
    mode: 'a+r'

- name: Add Docker repository
  ansible.builtin.shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: Install Docker Engine and Python SDK
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - python3-docker
    state: present
    update_cache: true

- name: Allow essential and Docker Swarm ports
  ansible.builtin.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - { port: '22', proto: 'tcp' }   # SSH
    - { port: '2377', proto: 'tcp' } # Swarm Management
    - { port: '7946', proto: 'tcp' } # Swarm Node Discovery
    - { port: '7946', proto: 'udp' } # Swarm Node Discovery
    - { port: '4789', proto: 'udp' } # Swarm Overlay Network

- name: Ensure UFW is enabled and reloaded
  ansible.builtin.ufw:
    state: enabled

- name: Ensure Docker service is started and enabled
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Add remote user to the docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true