---
# tasks file for roles/stack_deploy

- name: Ensure python3-venv and pip are installed
  ansible.builtin.apt:
    name:
      - python3-venv
      - python3-pip
    state: present
    update_cache: true

- name: Create a virtual environment for Ansible Docker modules
  ansible.builtin.command: python3 -m venv /opt/ansible-env
  args:
    creates: /opt/ansible-env

- name: Install required Python packages inside the virtual environment
  ansible.builtin.command: >
    /opt/ansible-env/bin/pip install docker jsondiff requests
  args:
    creates: /opt/ansible-env/lib/python3.*/site-packages/docker

- name: Set Python interpreter for Ansible to use the venv
  ansible.builtin.set_fact:
    ansible_python_interpreter: /opt/ansible-env/bin/python

- name: Define credentials
  ansible.builtin.set_fact:
    minio_root_user: "minioadmin"
    minio_root_password: "minioadmin"
    postgres_user: "prefect_user"
    postgres_password: "prefectuser"
  run_once: true

- name: Create MinIO root user secret
  community.docker.docker_secret:
    name: minio_root_user
    data: "{{ minio_root_user }}"
    state: present

- name: Create MinIO root password secret
  community.docker.docker_secret:
    name: minio_root_password
    data: "{{ minio_root_password }}"
    state: present

- name: Copy MinIO compose file to manager
  ansible.builtin.template:
    src: docker-compose.minio.yml.j2
    dest: /tmp/docker-compose.minio.yml

- name: Deploy MinIO stack
  community.docker.docker_stack:
    name: minio_stack
    state: present
    compose:
      - /tmp/docker-compose.minio.yml

- name: Copy Prefect compose file to manager
  ansible.builtin.template:
    src: docker-compose.prefect.yml.j2
    dest: /tmp/docker-compose.prefect.yml

- name: Deploy Prefect stack
  community.docker.docker_stack:
    name: prefect_stack
    state: present
    compose:
      - /tmp/docker-compose.prefect.yml