# This is the inventory file for the Docker Swarm setup.
# Please replace the placeholder IPs with the actual IP addresses of your VMs.

[managers]
# This group should contain one manager node.
manager-1 ansible_host=140.245.228.72 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/vc/Documents/Algo/pem_keys/ubuntu-72.key

[workers]
# This group can contain one or more worker nodes.
# For MinIO's native distributed mode, a minimum of 4 nodes (including the manager) is recommended.
worker-1 ansible_host=129.159.224.74 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/vc/Documents/Algo/pem_keys/ubuntu-74.key
# worker-2 ansible_host=192.168.1.102
# worker-3 ansible_host=192.168.1.103

[all:vars]
# If all your VMs share the same user and key, you can set them here.
# For example:
# ansible_user=ubuntu
# ansible_ssh_private_key_file=~/.ssh/your_private_key
