# This is the inventory file for the Docker Swarm setup.
# Please replace the placeholder IPs with the actual IP addresses of your VMs.

[managers]
# This group should contain one manager node.
#manager-1 ansible_host=13.48.84.49 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/vc/Documents/Algo/pem_keys/cluster-key.pem
manager-1 ansible_host=18.61.15.199 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/vc/Documents/Algo/pem_keys/cluster-key.pem

[workers]
# This group can contain one or more worker nodes.
# For MinIO's native distributed mode, a minimum of 4 nodes (including the manager) is recommended.
worker-1 ansible_host=18.60.107.64 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/vc/Documents/Algo/pem_keys/cluster-key.pem
worker-2 ansible_host=18.61.254.36 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/vc/Documents/Algo/pem_keys/cluster-key.pem
worker-3 ansible_host=18.60.41.31 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/vc/Documents/Algo/pem_keys/cluster-key.pem

[all:vars]
# If all your VMs share the same user and key, you can set them here.
# For example:
# ansible_user=ubuntu
# ansible_ssh_private_key_file=~/.ssh/your_private_key
#16.112.64.227
#18.61.127.205
#18.61.24.133
#98.130.45.111
