---
- name: Create Prefect home & flow dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ prefect_home }}"
    - "{{ prefect_flow_dir }}"

- name: Create venv
  ansible.builtin.command: "python3 -m venv {{ prefect_install_venv }}"
  args:
    creates: "{{ prefect_install_venv }}/bin/activate"

- name: Install Prefect
  ansible.builtin.command: "{{ prefect_install_venv }}/bin/pip install {{ ('prefect==' + prefect_version) if prefect_version else 'prefect' }}"

- name: Drop employee flow file (wired to spark:// master)
  ansible.builtin.template:
    src: employee_flow.py.j2
    dest: "{{ prefect_flow_file }}"
    mode: "0644"

- name: Create Prefect server systemd unit
  ansible.builtin.template:
    src: prefect-server.service.j2
    dest: /etc/systemd/system/prefect-server.service
    mode: "0644"

- name: Create Prefect agent systemd unit
  ansible.builtin.template:
    src: prefect-agent.service.j2
    dest: /etc/systemd/system/prefect-agent.service
    mode: "0644"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable & start Prefect server
  ansible.builtin.systemd:
    name: prefect-server
    state: started
    enabled: true

- name: Wait for Prefect API to be up
  ansible.builtin.uri:
    url: "{{ prefect_api_host }}/api/health"
    method: GET
    status_code: 200
  register: pref_up
  retries: 60
  delay: 2
  until: pref_up.status == 200

- name: Enable & start Prefect agent
  ansible.builtin.systemd:
    name: prefect-agent
    state: started
    enabled: true

- name: Build deployment
  ansible.builtin.shell: |
    source "{{ prefect_install_venv }}/bin/activate"
    prefect deployment build "{{ prefect_flow_file }}:{{ prefect_flow_name }}" \
      -n "{{ prefect_deployment_name }}" -q "{{ prefect_queue }}" \
      -o "{{ prefect_home }}/{{ prefect_deployment_name }}.yaml"
  args:
    chdir: "{{ prefect_home }}"

- name: Apply deployment
  ansible.builtin.shell: |
    source "{{ prefect_install_venv }}/bin/activate"
    prefect deployment apply "{{ prefect_home }}/{{ prefect_deployment_name }}.yaml"
