---
- name: Install base packages (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - wget
      - curl
      - tar
      - unzip
      - gnupg
      - ca-certificates
      - python3-venv
      - python3-pip
      - ufw
      - "{{ java_pkg }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install base packages (RedHat/CentOS)
  ansible.builtin.dnf:
    name:
      - wget
      - curl
      - tar
      - unzip
      - gnupg2
      - ca-certificates
      - python3
      - python3-pip
      - firewalld
      - java-17-openjdk-devel
    state: present
  when: ansible_os_family == "RedHat"


- name: Ensure MinIO data dir exists
  ansible.builtin.file:
    path: "{{ minio_data_dir }}"
    state: directory
    mode: "0755"
